apiVersion: 1

datasources:
  - name: InfluxDB-K6
    type: influxdb
    access: proxy
    url: http://k6-influxdb:8086
    database: k6
    user: admin
    password: admin123
    isDefault: true
    editable: true
    jsonData:
      httpMode: GET
      keepCookies: []
    secureJsonFields: {}
    version: 1
    readOnly: false

  - name: Prometheus-K6
    type: prometheus
    access: proxy
    url: http://k6-prometheus:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s
    version: 1
    readOnly: false